import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Container from "./components/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sans",
  description: "Generated by Next App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          `flex flex-col antialiased overflow-x-hidden min-h-screen background-content bg-gray-900`
        }
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
